window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("promise layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser statistics layout/default/layout_helper".split(" "),function(){var I=rea.FEATURES,R=Registry.get("promise"),n=Registry.get("crcrc").cr,d=Registry.get("crcrc").crc,g=Registry.get("i18n"),B=Registry.get("curtain"),q=Registry.get("helper"),S=Registry.get("layout/default/tabview"),r=Registry.get("layout/default/htmlutil"),T=Registry.get("statistics"),D=Registry.get("layout"),
E=Registry.get("layout/default/layout_helper"),x=E.images;D.render(function(){E.addStyle();E.addFont();var l=null,J="???",C=null,K="0.0.0",z=function(){var a=document.getElementById("ask"),c=d("div","content_wrapper","ask","main");if(a){var b=a.parentNode;b.removeChild(a);b.appendChild(c);document.body.setAttribute("class","main")}var a=d("div","head_container","ask","head_container"),b=d("div","tv_container_fit","ask","tv_container"),h=n("a","head_link","ask","head_link");h.href="http://tampermonkey.net";
h.target="_blank";var e=d("div","float","ask","head1"),f=d("img","banner","ask");f.src=rea.extension.getURL("images/icon128.png");var g=d("div","float head","ask","head2"),k=d("div","header_title","heading"),l=d("div","version","version","version");l.textContent=" by Jan Biniok";var m=n("div","search","box","");k.textContent="Tampermonkey";e.appendChild(f);g.appendChild(k);g.appendChild(l);h.appendChild(e);h.appendChild(g);a.appendChild(h);a.appendChild(m);c.appendChild(a);c.appendChild(b);c=S.create("_main",
b);a=n("div","main","main","tab_content_h");a.textContent=J;b=n("div","main","main","tab_content");c.appendTab(q.createUniqueId("main","main"),a,b).select();B.hide();return b},D=function(a){var c=a.script,b=d("div","viewer_bottom","bottom","");a=d("div","editor_400p_outer","editor",c.name);var h=d("div","editor_400p editor_border","editor",c.name);b.appendChild(a);a.appendChild(h);l.nocm?(a=d("textarea","editorta","editor",c.name),a.setAttribute("wrap","off"),h.appendChild(a),a.value=c.textContent):
window.setTimeout(function(){b.editor=new MirrorFrame(h,{value:c.textContent,noButtons:!0,matchBrackets:!0})},1);return b},U=function(){var a={};window.addEventListener("keydown",function(c){var d=!1;if("keydown"==c.type&&(a[c.keyCode]&&(d=a[c.keyCode](c)),d))return c.stopPropagation(),c.preventDefault(),!1},!0);return{registerListener:function(c,d){a[c]=d}}}(),t=function(a,c,b){q.select(b,function(a){return a.label}).forEach(function(b){var e=d("button",c,"tm",b.label);b.id&&e.setAttribute("data-btn-id",
b.id);if(b.icon){var f=n("img","tm",b.label,b.icon);f.src=x.get(b.icon);f.setAttribute("height","24px");e.appendChild(f)}f=n("span","tm",b.label,"label");f.textContent=b.label;e.appendChild(f);e.addEventListener("click",b.fn);a.appendChild(e);b.focus&&window.setTimeout(function(){$(e).focus()},300);b.keyDown&&U.registerListener(b.keyDown.keyCode?b.keyDown.keyCode:b.keyDown,b.keyDown.cb?b.keyDown.cb:b.fn)})},W=function(a){var c=a.script,b=d("div","viewer_last","install"),h=d("div","viewer_content",
"install_content"),e=d("div","ask_action_buttons","install_buttons"),f=[];f.push({label:a.messages.action,fn:function(){m(l.aid,"install")},focus:!0});I.RUNTIME.CHROME&&21>I.RUNTIME.BROWSER_VERSION&&f.push({label:a.messages.flags.install?g.getMessage("Process_with_Chrome"):null,fn:function(){V(c.fileURL);$(b).hide()}});f.push({label:g.getMessage("Cancel"),fn:w,keyDown:27});t(e,"install",f);h.appendChild(e);b.appendChild(h);return b},X=function(a){var c=d("div","viewer_last","import"),b=d("div","viewer_content",
"import_content"),h=d("div","ask_action_buttons import_buttons","import_buttons");t(h,"import",[{label:g.getMessage("Import"),fn:function(){var c=Object.keys(a.scripts);m(l.aid,"import",{data:{import_ids:c,global_settings:a.global_settings}})},focus:!0},{label:g.getMessage("Cancel"),fn:w,keyDown:27}]);b.appendChild(h);c.appendChild(b);b=d("div","section","btn");b.appendChild(c);return b},Y=function(a){a=d("div","viewer_last","ok");var c=d("div","viewer_content","ok_content"),b=d("div","ask_action_buttons",
"ok_buttons");t(b,"import",[{label:g.getMessage("Ok"),fn:w,focus:!0}]);c.appendChild(b);a.appendChild(c);return a},Z=function(a,c){var b=d("div","viewer_last","ok"),h=d("div","viewer_content","ok_content"),e=d("div","ask_action_buttons","ok_buttons");t(e,"permission",[{label:g.getMessage("Ok"),fn:function(){rea.permissions.request({permissions:[c.permission]},function(a){rea.runtime.lastError&&console.warn("notify: error on getting permission",c.permission+"!","reason:",rea.runtime.lastError.message);
m(l.aid,"permission",{data:{granted:a,permission:c.permission}})})},focus:!0},{label:g.getMessage("Cancel"),fn:w,keyDown:27}]);h.appendChild(e);b.appendChild(h);var h=d("div","viewer_upper","permission"),e=d("div","viewer_info viewer_info_wide","general","permission"),f=d("div","viewer_content","general_content","permission"),y=n("h3","install","heading","permission"),k=d("span","message","heading","permission");y.textContent=c.title;k.textContent=c.message;f.appendChild(k);e.appendChild(y);e.appendChild(f);
h.appendChild(e);e=d("div","section","perm_src","permission");e.appendChild(h);e.appendChild(b);a.appendChild(e)},ba=function(a,c){var b=Date.now(),h,e;c.timeout&&(h=window.setTimeout(function(){w();f()},c.timeout));var f=function(){var a;e&&window.clearInterval(e);h&&window.clearTimeout(h);e=h=null;(a=$("button[data-btn-id]")[0])&&a.parentNode.removeChild(a)},y=d("div","viewer_last","ok"),k=d("div","viewer_content","ok_content"),r=d("div","ask_action_buttons","ok_buttons"),L=d("div","ask_action_buttons",
"ok_buttons"),p=d("div","ask_action_buttons","ok_buttons");t(r,"connect",[{label:g.getMessage("Allow_once"),icon:"button_ok",fn:function(){return m(l.aid,"connect",{data:{ok:!0,allow:!0,once:!0}})},focus:!0},{label:g.getMessage("Temporarily_allow"),icon:"clock",fn:function(){return m(l.aid,"connect",{data:{ok:!0,allow:!0,temporary:!0}})}},{label:c.hostname!=c.domain?g.getMessage("Always_allow"):g.getMessage("Always_allow_domain"),icon:"edit_add",fn:function(){return m(l.aid,"connect",{data:{ok:!0,
allow:!0}})}},function(){return c.hostname!=c.domain?{label:g.getMessage("Always_allow_domain"),icon:"edit_add",fn:function(){return m(l.aid,"connect",{data:{ok:!0,allow:!0,whole_domain:!0}})}}:null}(),function(){return c.all_domains?{label:g.getMessage("Always_allow_all_domains"),icon:"critical",fn:function(){f();if(window.confirm(g.getMessage("This_gives_this_script_the_permission_to_retrieve_and_send_data_from_and_to_every_webpage__This_is_potentially_unsafe__Are_you_sure_you_want_to_continue_")))return m(l.aid,
"connect",{data:{ok:!0,allow:!0,all_domains:!0}})}}:null}()].filter(function(a){return a}));t(L,"connect",[{label:g.getMessage("Forbid_once"),icon:"cancel",fn:function(){return m(l.aid,"connect",{data:{ok:!0,deny:!0,once:!0}})},keyDown:27},{label:c.hostname!=c.domain?g.getMessage("Always_forbid"):g.getMessage("Always_forbid_domain"),icon:"no",fn:function(){return m(l.aid,"connect",{data:{ok:!0,deny:!0}})}},function(){return c.hostname!=c.domain?{label:g.getMessage("Always_forbid_domain"),icon:"no",
fn:function(){return m(l.aid,"connect",{data:{ok:!0,deny:!0,whole_domain:!0}})}}:null}(),{label:g.getMessage("Dont_ask_again"),icon:"exit",fn:function(){return m(l.aid,"connect",{data:{ok:!0,deny:!0,all_domains:!0}})}}].filter(function(a){return a}));t(p,"connect_misc",[function(){return c.tabid?{label:g.getMessage("Focus_tab"),icon:"windowlist",fn:function(){aa("focus_tab",{tabid:c.tabid})}}:null}(),function(){if(c.timeout)return e=window.setInterval(function(){var a;(a=$("button[data-btn-id]")[0])&&
$(a).find("span").text(g.getMessage("Skip_timeout__0seconds0_seconds_",Math.round((c.timeout+b-Date.now())/1E3)))},1E3),{label:g.getMessage("Skip_timeout__0seconds0_seconds_",Math.round(c.timeout/1E3)),id:"skip_timeout_button",fn:f}}()].filter(function(a){return a}));var q=d("div","viewer_upper","connect"),u=d("div","viewer_info viewer_info_wide","general","connect"),v=d("div","viewer_content","general_content","connect"),F=n("h3","install","heading","connect"),M=d("span","message","heading","connect");
if(c.script.icon){var A=n("img","version","heading","connect");A.src=c.script.icon;F.appendChild(A)}F.textContent=g.getMessage("A_userscript_wants_to_access_a_cross_origin_resource_");var A=d("div","ask_action_buttons message","help","connect"),N=n("div","help","connect"),G=g.getMessage("A_request_to_a_cross_origin_resource_is_nothing_unusual__You_just_have_to_check_whether_this_script_has_a_good_reason_to_access_this_domain__For_example_there_are_only_a_very_few_reasons_for_a_userscript_to_contact_your_bank__Please_note_that_userscript_authors_can_avoid_this_dialog_by_adding_@connect_tags_to_their_scripts__You_can_change_your_opinion_at_any_time_at_the_scripts_settings_tab_",
c.connect_url,c.settings_url),G=G.replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/\[url=([^\]]+)\](.*)\[\/url\]/g,'<a target="_blank" href="$1">$2 &#x2B00;</a>').replace(/\n/g,"<br>");N.innerHTML=G+"<br><br>";A.appendChild(N);k.appendChild([p,A,r,L]);y.appendChild(k);var O=d("table","script_desc","connect");[{prop:"name",label:g.getMessage("Name")},{prop:"src_url",label:g.getMessage("Tab_URL")},{prop:"hostname",label:g.getMessage("Destination_domain")},{prop:"url",label:g.getMessage("Destination_URL")}].forEach(function(a){var b=
c[a.prop]||c.script[a.prop]||a.value,f=d("tr","script_desc",a.prop,"connect"),e=d("td","script_desc",a.prop,"connectdt"),h=d("td","script_desc",a.prop,"connectdd");e.textContent=a.label?a.label:"";h.textContent=b||g.getMessage("_not_set_");f.appendChild(e);f.appendChild(h);O.appendChild(f)});M.appendChild(O);v.appendChild(M);u.appendChild(F);u.appendChild(v);q.appendChild(u);k=d("div","section","connect_src","connect");k.appendChild(q);k.appendChild(y);a.appendChild(k)},da=function(a,c){a.appendChild(X(c));
if(c.global_settings){var b=d("div","viewer_upper","");ca({content:b});a.appendChild(b)}c.scripts&&Object.keys(c.scripts).forEach(function(b){var e=c.scripts[b];b=d("div","viewer_upper",b);H({content:b,preparat:e},!0);a.appendChild(b)})},ca=function(a){a=a.content;var c=d("div","viewer_upper","global_settings"),b=d("div","viewer_info viewer_info_wide","general","global_settings"),h=d("div","viewer_content","general_content","global_settings"),e=n("h3","install","heading","global_settings"),f=n("img",
"version","heading","global_settings");f.src=rea.extension.getURL("images/icon48.png");e.appendChild(f);f=n("span","name","heading","global_settings");f.textContent=g.getMessage("Global_Settings");e.appendChild(f);b.appendChild(e);var e=d("table","script_desc","global_settings"),f=d("tr","settings_desc","action","global_settings"),l=d("td","settings_desc","action","global_settingsdt"),k=d("td","settings_desc","action","global_settingsdd");l.textContent=g.getMessage("Action");k.textContent=g.getMessage("Global_settings_import");
f.appendChild(l);f.appendChild(k);e.appendChild(f);f=d("tr","settings_desc","warning","global_settings");l=d("td","settings_desc","warning","global_settingsdt");k=d("td","settings_desc","warning","global_settingsdd");l.innerHTML='<img src="'+x.get("critical")+'"></img>&nbsp;';k.textContent=g.getMessage("This_will_overwrite_your_global_settings_");f.appendChild(l);f.appendChild(k);e.appendChild(f);h.appendChild(e);b.appendChild(h);c.appendChild(b);b=d("div","section","settings_src");b.appendChild(c);
a.appendChild(b)},H=function(a,c){var b=a.preparat,h=a.content,e=b.script||{},f=e.uuid||e.id||e.name;b.short_info||(b.short_info=[]);var l=d("div","viewer_upper",f),k=d("div","viewer_info "+(c?"viewer_info_wide":"viewer_info_multiple"),"general",f),m=d("div","viewer_content","general_content",f),q=n("h3","install","heading",f);if(e.icon||e.icon64){var p=n("img","version","heading",f);p.src=e.icon||e.icon64;q.appendChild(p)}p=n("span","name","heading",f);p.textContent=b.heading||e.name||"";q.appendChild(p);
e.version&&(p=d("span","view_version","heading",f),p.textContent="v"==e.version[0]?"":"v",p.textContent+=e.version,q.appendChild(p));k.appendChild(q);c&&b.short_info.unshift({prop:"heading",value:b.messages.heading,label:g.getMessage("Action")});var t=d("table","script_desc",f);b.short_info.forEach(function(a){var b=e[a.prop]||a.value;if(b||!c){var h=d("tr","script_desc",a.prop,f),l=d("td","script_desc",a.prop,f+"dt"),k=d("td","script_desc",a.prop,f+"dd");l.textContent=a.label?a.label:"";k.textContent=
b||g.getMessage("_not_set_");h.appendChild(l);h.appendChild(k);t.appendChild(h)}});m.appendChild(t);var q=d("div","viewer_info viewer_info_multiple","info",f),u;c?u=m:(u=d("div","viewer_content","info_content",f),p=n("h4","action","heading",f),p.textContent=b.messages.heading,u.appendChild(p));var v=0;["errors","warnings","info"].forEach(function(a){var c=n("table",a,f+v);(b.messages[a]||[]).forEach(function(b){v++;var d=n("tr",a,f+v),e=n("td",a,f+"dt"+v),h=n("td",a,f+"dd"+v);"info"==a?b.label&&b.value?
(e.textContent=b.label,h.textContent=b.value):(e.innerHTML='<img src="'+x.get("info")+'"></img>&nbsp;',h.innerHTML=r.safeTagsReplace(b).replace(/\n/,"<br />")):"warnings"==a?(e.innerHTML='<img src="'+x.get("critical")+'"></img>&nbsp;',h.innerHTML=r.safeTagsReplace(b).replace(/\n/,"<br />")):"errors"==a&&(e.innerHTML='<img src="'+x.get("error")+'"></img>&nbsp;',h.innerHTML=r.safeTagsReplace(b).replace(/\n/,"<br />"));d.appendChild(e);d.appendChild(h);c.appendChild(d)});u.appendChild(c)});p=function(a,
b,c,h){var l=n("table",a,f),k=0,m={};b.forEach(function(b){if(!(k>h||m[b])){m[b]=!0;var e=d("tr",a+"desc",b,f+k),g=d("td",a+"desc",b,f+k+"dt"),n=d("td",a+"desc",b,f+k+"dd");g.innerHTML=0==k?r.safeTagsReplace(c.label):"&nbsp;";n.innerHTML=k==h?'<span title="'+r.safeTagsReplace(c.warning)+'">...!</span>':r.safeTagsReplace(b);e.appendChild(g);e.appendChild(n);l.appendChild(e);k++}});if(e.options&&(b=e.options.override&&e.options.override["use_"+a])&&b.length){b=d("tr",a+"desc","ovverride",f+k);var p=
d("td",a+"desc","ovverride",f+k+"dt"),q=d("td",a+"desc","ovverride",f+k+"dd");p.innerHTML=0==k?r.safeTagsReplace(c.label):"&nbsp;";q.innerHTML=r.safeTagsReplace(" ("+g.getMessage("overwritten_by_user")+")");b.appendChild(p);b.appendChild(q);l.appendChild(b)}u.appendChild(l)};p("includes",(e.includes||[]).concat(e.matches||[]),{label:g.getMessage("Include_s__"),warning:g.getMessage("Attention_Can_not_display_all_includes_")},5);p("excludes",e.excludes||[],{label:g.getMessage("Exclude_s__"),warning:g.getMessage("Attention_Can_not_display_all_excludes_")},
3);k.appendChild(m);q.appendChild(u);l.appendChild(k);l.appendChild(q);k=d("div","section",f,"install_src");k.appendChild(l);a.install&&k.appendChild(a.install(b));a.editor&&k.appendChild(a.editor(b));h.appendChild(k)},V=function(a){m(l.aid,"abort");window.setTimeout(function(){window.location=a+"#bypass=true"},10)},w=function(a){m(l.aid,"abort");window.setTimeout(function(){window.close()},3E3)},P=function(a,c){m(l.aid,"unload");C&&(window.clearInterval(C),C=null);window.removeEventListener("unload",
P)};window.addEventListener("unload",P);var Q=function(){window.location.search||window.location.hash?(l=q.getUrlArgs(),l.aid?(m(l.aid,"preparat").done(function(a){a.ext&&a.ext.version&&(K=a.ext.version);a.i18n&&g.setLocale(a.i18n);a.options&&a.options.statistics_enabled&&T.init("ask",K);J=g.getMessage("Install");var c=null;a.preparat&&("install"==a.type?c=function(){H({content:z(),preparat:a.preparat,install:W,editor:D})}:"install_error"==a.type?c=function(){H({content:z(),preparat:a.preparat,install:Y},
!0)}:"import"==a.type?c=function(){da(z(),a.preparat)}:"permission"==a.type?c=function(){Z(z(),a.preparat)}:"connect"==a.type&&(c=function(){ba(z(),a.preparat)}),C=window.setInterval(ea,3E3),c&&window.setTimeout(c,1))}).fail(function(){w()}),B.wait(g.getMessage("Please_wait___"))):w()):window.onhashchange=function(){Q()}},ea=function(){return m(l.aid,"ping",{bg:!0})},m=function(a,c,b){b=b||{};var d=R();try{var e={aid:a,method:c};b.data&&q.each(b.data,function(a,c){e[c]=b.data[c]});sendMessage({method:"askCom",
data:e},function(a){b.bg||B.hide();a.error?(a.please_close&&window.setTimeout(window.close,100),d.reject(a)):d.resolve(a)});b.bg||B.wait(g.getMessage("Please_wait___"))}catch(f){console.warn("sS: "+f.message),d.reject()}return d.promise()},aa=function(a,c,b){try{sendMessage(q.assign({method:"buttonPress",name:a},c),function(a){b&&b(a)})}catch(d){console.log("button: "+d.message)}};rea.extension.onMessage.addListener(function(a,c,b){if("confirm"==a.method)q.confirm(a.msg,function(a){b({confirm:a})});
else if("showMsg"==a.method)q.alert(a.msg),b({});else return!1;return!0});Q()})});
