Registry.require(["promise","syncinfo"],function(){(function(g){var r=Registry.get("promise"),z=Registry.get("syncinfo"),t=function(a,c){a&&c&&Object.keys(c).forEach(function(b){a[b]=c[b]})},f=function(a,c){var b;if("string"===typeof l)b="G";else{b=l.tracker[a||"default"];if(null===b)return;b=(b||l.tracker["default"]).match(/[0-9]*/g).join("").split("").map(function(a){return String.fromCharCode(a.charCodeAt(0)+23)}).join("")}return[b].concat(c?[c]:[]).join(".")},m=function(){return{tracker:"default UA-40782729-1 script UA-40782729-2 script_update UA-40782729-2 naverr UA-40782729-3".split(" ")}},
u=function(){return"UA-40861355-1"},v=function(){return"UA-57518333-1"},p={"default":m,gcal:m,G3XV:m,fire:m,neuu:v,jecn:v,dhdg:function(){return{options:["default",{sampleRate:1}],tracker:["script","UA-40861355-2","script_update","UA-40861355-3","error","UA-40861355-4","naverr","UA-40861355-5","default","UA-40861355-6","browser",null]}},dcgo:u,bnim:u,mfdh:m,heif:m},l=function(a){var c=a();"string"===typeof c&&(c={tracker:["default",c]});var b,d={options:{},tracker:{}};Object.keys(d).forEach(function(a){if(c[a])for(b=
0;b<c[a].length;b+=2)d[a][c[a][b]]=c[a][b+1]});return d}(p[rea.runtime.short_id]||p["default"]),A=[{msg:"a disconnected port"},{msg:"Function.prototype.apply: Arguments list has wrong type",url:"event_bindings"},{msg:"Script error."}],w=!1,x=!1,h=!1;g._gaq=g._gaq||[];var n=[],B=function(){(function(a,c,b,d){a.GoogleAnalyticsObject="ga";a.ga=a.ga||function(){(a.ga.q=a.ga.q||[]).push(arguments)};a.ga.l=1*new Date;b=c.createElement("script");d=c.getElementsByTagName("script")[0];b.async=!0;b.src="https://ssl.google-analytics.com/analytics.js";
b.addEventListener("load",function(){for(var a;a=n.shift();)a();n=!1},!1);d.parentNode.insertBefore(b,d)})(g,document)},k=function(a){if(a){var c=arguments;y().done(function(){g.ga.apply(g,c)})}},D=function(){x||(n.push(function(){var a=[],c={};Object.keys(l.tracker).forEach(function(b){var d=f(b);if(d&&!c[d]){c[d]=!0;var e={name:d};t(e,null);t(e,(l.options||{})[b]);a.push(["create",l.tracker[b],"auto",e]);a.push([d+".set","checkProtocolTask",null]);a.push([d+".set","anonymizeIp",!0]);a.push([d+".set",
"forceSSL",!0])}});a.forEach(function(a){g.ga.apply(g,a)});k(f("pageview","send"),"pageview",g.location.pathname||g.location.href);p[rea.runtime.short_id]||window.setTimeout(C,3E4)}),B(),x=!0)},C=function(){h&&k(f("extension","send"),"event","Extension","ID",rea.runtime.id+" @ "+navigator.userAgent,null,{nonInteraction:!0})},q=function(a,c,b){if(h&&a.search){void 0===c&&(c="");void 0===b&&(c+=" "+window.location.href,b="");var d=!1;A.forEach(function(b){if(b.msg||b.url)b.msg&&-1==a.search(b.msg)||
b.url&&-1==c.search(b.url)||(d=!0)});d||k(f("error","send"),"event","Error",a,c+":"+b,null,{nonInteraction:!0})}},y=function(){var a=r();!1===n?a.resolve():n.push(a.resolve);return a.promise()},E=function(){var a=null,c;return function(){return c?c:null===a?c=z.getUtc().then(function(b){c=null;a=b.getTime()-Date.now();window.setTimeout(function(){a=null},6E4);return a}).fail(function(){window.setTimeout(function(){c=null},6E5)}):r.Pledge(a)}}();Registry.register("statistics","5271",{init:function(a,
c){window.onerror=function(b,d,e,g,f){var h="";if(f)try{h=f.stack}catch(k){}q(b,c+" "+a+"@"+rea.extension.urls.prepareForReport(d),[e+":"+g,h].join(";"))};document.onsecuritypolicyviolation=function(b){var d="";if(b)try{d=b.stack}catch(e){}q("CSP violation of "+b.effectiveDirective,c+" "+a+"@"+rea.extension.urls.prepareForReport(b.documentURI),[b.sourceFile," -> ",b.lineNumber+":"+b.columnNumber,d].join(";"))};w=!0},setEnabled:function(a){w&&!Registry.isDevVersion("statistics")&&(h=a)&&D()},tB:function(a){if(h){var c=
"";a.updated&&(c="Updated");k(f("browser","send"),"event","Browser",c,navigator.userAgent,null,{nonInteraction:!0})}},tS:function(a,c,b){if(h){var d="",e;"i"===b?(d="Installed",a+=" <"+(c?c:"?")+">"):"u"===b?(d="Updated",e=f("script_update","send")):"b"===b?(d="Blacklisted",a+=" <"+(c?c:"?")+">"):"m"===b?(d="Revealed",a=c):d="Removed";k(e||f("script","send"),"event","Script",d,a,null,{nonInteraction:!1})}},tE:q,tG:function(a,c,b){if(h){var d="",e="";"clicked"===a?(e="Click",d=c+":"+b):"button"===
a?(e="Button",d=c):"dialog"===a&&(e="Dialog");k(f("begging","send"),"event","Begging",e,d,null,{nonInteraction:!1})}},tN:function(a,c,b){if(h){var d;E().then(function(a){d=a;return y()}).done(function(){k(f("naverr","send"),"pageview",a,{metric1:b,dimension1:g.ga.getByName(f()).get("clientId"),dimension2:String(Date.now()+d),nonInteraction:!1})})}}})})(window)});
