Registry.require(["promise","helper","convert","xmlhttprequest"],function(){var g=Registry.log,F=rea.FEATURES,d=Registry.get("promise"),D=Registry.get("helper"),G=Registry.get("convert"),H=Registry.get("xmlhttprequest").run,p=0,l=0,v={ePASTEBIN:1,eCHROMESYNC:2,eGOOGLEDRIVE:3},z=[],C=!1,w=null,J=[{method:"HEAD",url:"https://www.google.com",extract:function(d,g){try{for(var k=g?g.split("\n"):[],h=0;h<k.length;h++){var n=k[h].split(":"),M=n.shift()||"",I=n.join(":")||"";if("date"==M.trim().toLowerCase()&&
I)return new Date(I)}}catch(p){}return null}},{method:"GET",url:"https://json-time.appspot.com/time.json",extract:function(d){try{var g=JSON.parse(d);if(!g.error&&g.datetime)return new Date(g.datetime)}catch(k){}return null}}],u=function(){var f=function(){var n,f=!1,h=null,k=function(a){},r=function(a){h=a.state;g.log("si: sync filesystem state changed to : "+h)},p=function(){var a=d(),e=function(b){g.warn("si: listFiles() error:",b);a.reject()};n.root.getDirectory("/",{create:!0},function(b){var A=
b.createReader(),c=[],d=function(){A.readEntries(function(b){b.length?(c=c.concat(b),d()):a.resolve(c)},e)};d()},e);return a.promise()},l=function(a,e){var b=d(),A=function(e){g.warn("si: writeFileData(",a,") error:",e);b.reject()};n.root.getDirectory("/",{create:!0},function(c){c.getFile(a,{create:!0},function(a){a.createWriter(function(a){a.onwriteend=function(c){a.onwriteend=function(a){b.resolve()};a.onerror=A;c=new Blob([e],{type:"text/plain"});a.write(c)};a.truncate(0)},A)},A)},A);return b.promise()},
t=function(a){var e=d(),b=function(b){g.warn("si: getFileData(",a,") error:",b);e.reject()},c=function(a){var c=new FileReader;c.onloadend=function(){e.resolve(this.result)};c.onerror=b;c.onabort=b;c.readAsText(a)};n.root.getDirectory("/",{create:!0},function(e){e.getFile(a,{},function(a){a.file(function(a){c(a)},b)},b)},b);return e.promise()},q=function(a){var e=d(),b=function(b){g.warn("fileStorage: deleteFile(",a,") error:",b);e.reject()};n.root.getDirectory("/",{create:!0},function(c){c.getFile(a,
{create:!1},function(a){a.remove(e.resolve,b)},b)},b);return e.promise()},m=null,y={},c=function(){return B(function(){var a=d(),e=[];D.each(y,function(a,c){e.push(function(){var e=d();l(c,a).always(function(){e.resolve()});return e.promise()}())});y={};d.when(e).done(function(){a.resolve()});return a.promise()})};return{init:function(){if(!f){try{rea.syncFileSystem.onFileStatusChanged.addListener(k)}catch(e){g.verbose("si: error registering file status callback: "+e.message)}if(F.SYNC.GOOGLE_DRIVE.HAS_SERVICE_STATUS)try{rea.syncFileSystem.onServiceStatusChanged.addListener(r)}catch(e){g.verbose("si: error registering service status callback: "+
e.message)}f=!0}var a=d();rea.syncFileSystem.supported?rea.syncFileSystem.requestFileSystem(function(e){rea.runtime.lastError?a.resolve(!1):(n=e,a.resolve(!0))}):a.resolve(!1);return a.promise()},list:function(){return p().then(function(a){var e=[],b=[],c=d(),m=/.user.js$/;a.forEach(function(a){-1!=a.search(m)&&b.push(function(){var b=d();t(a).done(function(a){var b;try{b=JSON.parse(a)}catch(c){}b&&e.push({uuid:b.uuid,url:b.url,options:b.options?b.options:{},content:b.content})}).always(function(){b.resolve()});
return b.promise()}())});d.when(b).done(function(){c.resolve(e)});return c.promise()})},add:function(a){y[a.uuid+".user.js"]=JSON.stringify({uuid:a.uuid,url:a.url,options:a.options,content:a.content});m&&window.clearTimeout(m);m=window.setTimeout(c,3E3);return d.Pledge()},write:c,remove:function(a){var e={uuid:a.uuid,url:a.url,options:a.options||{}};e.options.removed=Date.now()+w;y[a.uuid+".user.js"]=JSON.stringify(e);m&&window.clearTimeout(m);m=window.setTimeout(c,3E3);return d.Pledge()},reset:function(){return p().then(function(a){var c=
[],b=d();a.forEach(function(a){c.push(function(){var b=d();q(a).always(function(){b.resolve()});return b.promise()}())});d.when(c).done(function(){b.resolve()});return b.promise()})}}}(),r=function(){var n=!1,f,h=function(c,a){if(p==v.eCHROMESYNC&&"sync"==a)if(null===w)E().done(function(){h(c,a)});else{var e=new RegExp(f+"$");c&&Object.keys(c).forEach(function(b){var d=c[b];g.verbose('si: storage key "%s" in namespace "%s" changed. Old value was "%s", new value is "%s".',b,a,d.oldValue,d.newValue);
if(-1==b.search(e))g.verbose("si:   ^^ ignore cause this is not related to us!");else for(var m=0;m<z.length;m++)if(q[b])g.verbose("si:   ^^ ignore cause object is going to be changed right now or was changed by me!");else{var f=u(d.newValue,b);if(f)z[m](b,f)}})}},k=function(c,a){var e=d(),b=[];a?r().done(function(d){"url"==c&&(a=a.split("#")[0]);b=D.select(d,function(b){return b.item&&b.item[c]==a});e.resolve(b)}).fail(function(a){e.reject(a)}):e.resolve(b);return e.promise()},r=function(){return B(function(){var c=
d(),a=new RegExp(f+"$");rea.storage.sync.get(null,function(e){var b=[];e&&Object.keys(e).forEach(function(c){-1!=c.search(a)&&b.push({key:c,item:u(e[c],c)})});c.resolve(b)});return c.promise()})},u=function(c,a){var e=null;try{e=JSON.parse(c)}catch(b){}return e&&e.url?e:(g.verbose("si: unable to parse extended info of "+a),null)},x=function(c){return c.then(function(a){var c={};a=D.select(a,function(a,b){if(!c[a.key])return c[a.key]=!0});if(1<a.length){var b=d(),f=[],g=a.pop();a.forEach(function(a){f.push(m(a.key))});
d.when(f).done(function(){b.resolve(g)});return b.promise()}return d.Pledge(a[0])})},t=null,q={},m=function(c,a){return B(function(){var a=d();rea.storage.sync.remove(c,function(b){(b=rea.runtime.lastError)?a.reject(b):a.resolve()});return a.promise()})},y=function(c){return B(function(){var a=d();rea.storage.sync.set(q,function(c){(c=rea.runtime.lastError)?a.reject(c):(q={},a.resolve())});return a.promise()})};return{init:function(){var c=!0;if(!n)try{rea.storage.onChanged.addListener(h),n=!0}catch(a){g.verbose("si: error registering sync callback: "+
a.message),c=!1}2==l?f="@v2":(l=1,f="@us");return d.Pledge(c)},list:function(){var c;c=null===w?E():d.Pledge();return c.then(function(){return r()}).then(function(a){var c=new RegExp(f+"$"),b=[];a.forEach(function(a){var d=a.key;a=a.item;var m=d.replace(c,""),f=null;(f=q[d]?u(q[d],d):a)&&(1==l||(!f.vmin||l>=f.vmin)&&(!f.vmax||l<=f.vmax))&&b.push({id:m,uuid:f.uuid,url:f.url,options:f.options||{}})});return d.Pledge(b)})},add:function(c){var a=d(),e=2==l?k("uuid",c.uuid):k("url",c.url);x(e).done(function(b){var e;
b?(e=b.key,b=b.item):(e=c.uuid+f,b={});b.url=c.url;b.options=c.options||{};2==l&&(b.uuid=c.uuid);q[e]=JSON.stringify(b);t&&window.clearTimeout(t);t=window.setTimeout(y,3E3);a.resolve()});return a.promise()},remove:function(c){var a=d(),e=2==l?k("uuid",c.uuid):k("url",c.url);x(e).done(function(b){var e;b?(e=b.key,b=b.item):(e=c.uuid+f,b={});b.options=b.options||{};b.options.removed=Date.now()+w;q[e]=JSON.stringify(b);t&&window.clearTimeout(t);t=window.setTimeout(y,3E3);a.resolve()});return a.promise()},
reset:function(){return B(function(){var c=d();rea.storage.sync.clear(function(){q={};c.resolve()});return c.promise()})}}}(),k=function(){var f,k=null,h=function(){var m=d();f?H({method:"GET",retries:3,url:f},{onload:function(d){4==d.readyState&&(200==d.status?m.resolve(d.responseText):m.reject())},onerror:m.reject}):m.reject({});return m.promise()},r=function(){var f=d();h().done(function(d){l(d).done(function(c){k=G.MD5(d);f.resolve(c)})}).fail(function(d){f.reject(d)});return f.promise()},l=function(f){var k=
d(),c=[];try{f=f.replace(/\t/g,"    ");f=f.replace(/\r/g,"\n");f=f.replace(/\n\n+/g,"\n");for(var a=f.split("\n"),e=0;e<a.length;e++){var b=a[e],h=b.split("|");if(3<h.length)g.log("si: can't handle line: "+b);else{var n=h[h.length-1],r=null,p=null;if(1<h.length)for(var l=h.length-2;0<=l;l--)try{r=JSON.parse(h[l])}catch(q){p=h[l]}c.push({name:p,url:n,options:r||{}})}}}catch(q){g.warn("si: unable to parse data: "+f)}k.resolve(c);return k.promise()},u=function(){var f=d();h().done(function(d){l(d).done(function(c){if(k!=
G.MD5(d))for(c=0;c<z.length;c++)z[c]()})}).fail(function(d){f.reject(d)});return f.promise()},x=null,t=function(d){if(x)if(d)window.clearTimeout(x);else return;g.verbose("si: schedule sync for periodical run every 18000000 ms");x=window.setTimeout(function(){x=null;p==v.ePASTEBIN&&u().always(function(){t()})},18E6)},q={init:function(h){f="https://pastebin.com/raw.php?i=%s".replace("%s",h);t(!0);return d.Pledge(!0)},list:function(){return null===w?E().then(function(){return q.list()}):r()}};return q}(),
h={};h[v.ePASTEBIN]=k;h[v.eCHROMESYNC]=r;F.SYNC.GOOGLE_DRIVE.SUPPORTED&&(h[v.eGOOGLEDRIVE]=f);return h}(),K=function(){var f=d(),g=0,k=function(){if(g<J.length){var d=J[g];H({method:d.method,url:d.url},{ondone:function(n){4==n.readyState&&200==n.status?(n=d.extract(n.responseText,n.responseHeaders),null===n?(g++,window.setTimeout(k,1)):f.resolve(n)):(g++,window.setTimeout(k,1))}})}else f.reject(void 0)};k();return f.promise()},E=function(){g.verbose("si: determine time offset");var f=d();K().done(function(d){w=
d.getTime()-Date.now();g.verbose("si: detected a time offset of "+w+" ms")}).fail(function(){w=0;g.log("si: time offset detection failed!")}).always(f.resolve);return f.promise()},B=function(f,l){var k=d();void 0===l&&(l=3);var h=function(){if(C)window.setTimeout(h,500);else{C=!0;try{f().always(function(){C=!1}).done(function(){k.resolve.apply(this,arguments)}).fail(function(){0<--l?(g.log("si: some retries left, wait for",6E4,"ms"),window.setTimeout(h,6E4)):(g.warn("si: no retries left, skipping this sync request!"),
k.reject("no retries left"))})}catch(d){g.warn(d),C=!1,k.reject(d)}}};h();return k.promise()},L={init:function(f,g,k){z=[];p=f;l=g;return u[p]?u[p].init(k).done(function(d){}):d.Breach()},getUtc:K,debug:function(d){},addChangeListener:function(d){z.push(d)},isWritable:function(){return p==v.eCHROMESYNC||p==v.eGOOGLEDRIVE},types:v};["list","add","reset","remove"].forEach(function(f){L[f]=function(){return u[p]&&u[p][f]?u[p][f].apply(this,arguments):d.Pledge()}});Registry.register("syncinfo","5271",
L)});
