Registry.require(["helper","convert"],function(){var n=Registry.get("helper"),q=Registry.get("convert"),w,r,z=function(a){var f=n.isLocalImage(a);return a&&"http"==a.substr(0,4)||f},A={cookie:!0,"user-agent":!0,referer:!0,origin:!0,host:!0,"proxy-connection":!0,"accept-encoding":!0,"accept-charset":!0},D={"Cache-Control":"no-cache",Pragma:"no-cache"},t=function(a){return{responseXML:"",responseText:"",response:null,readyState:4,responseHeaders:"",status:0,statusText:"",error:a||"Forbidden"}},u=function(a){if("Blob"===
a.type)return new Blob([q.str2arrbuf(a.value)]);if("File"===a.type)return new File([q.str2arrbuf(a.value)],a.name,{type:a.meta,lastModified:a.lastModified||Date.now()});if("FormData"==a.type){var f=new FormData;Object.keys(a.value).forEach(function(b){var c="Array"===a.value[b].type,g=u(a.value[b]),e=c?g:[g];e.forEach(function(a,c){f.append(b,e[c])})});return f}if("Array"===a.type||"Object"===a.type){var k,c,g;"Object"===a?(g=Object.keys(a.value),c=function(a){return a<g.length?g[a]:null},k={}):(c=
function(b){return b<a.value.length?b:null},k=[]);for(var l,b=0;null!==(l=c(b));b++)k[l]=u(a.value[l]);return k}return a.value},E=function(a,f,k){void 0===k&&(k={});var c=n.assign({},f||{}),g=function(a,b){if(c[a])c[a]("function"==typeof b?b():b)};f=function(a,b){c[a]&&(g(a,b),c[a]=null)};if(k.internal||z(a.url)){var l=window.fetch&&a.url&&"http"==a.url.substr(0,4),b=!r&&a.anonymous,d=a.fetch;return l&&(b||d)?B(a,c,k,f,g):y(a,c,k,f,g)}console.warn("xhr: invalid scheme of url:",a.url);a=t("Invalid scheme");
f("onerror",a);f("ondone",a)},C="TM-finalURL"+rea.runtime.short_id,B=function(a,f,k,c,g){var l=function(a){var b=[],c;a.headers&&(c=a.headers.get(C)||a.url,a.headers.forEach(function(a,h){h.toLowerCase()!=C.toLowerCase()&&b.push(h+":"+a)}));return{readyState:4,responseHeaders:b.join("\n"),finalUrl:c,status:a.status,statusText:a.statusText}},b=function(b){(function(a,b){for(var m=[],h=0,c=a.length;h<c;h+=b)m.push(a.slice(h,b+h));return m})(b,parseInt(a.partialSize)).forEach(function(a){g("onpartial",
{partial:a})})};try{var d={};d.method=a.method||"GET";d.redirect="follow";a.nocache&&(d.cache="no-store");d.credentials=a.anonymous?"omit":"include";if(a.headers){var n={};Object.keys(a.headers).forEach(function(b){var c=b;A[b.toLowerCase()]&&(c=w+b);n[c]=a.headers[b]});d.headers=new window.Headers(n)}void 0!==a.data&&(d.body="typified"===a.data_type?u(a.data):"string"===typeof a.data?a.data:JSON.stringify(a.data));void 0!==a.timeout&&(d.timeout=a.timeout);var p=window.fetch(a.url,d).then(function(e){var d=
l(e);200!=d.status&&0!=d.status?0<a.retries?(a.retries--,B(a,f,k,c,g)):(c("onerror",d),c("ondone",d)):function(){var b;if(e.ok)void 0!==a.responseType?function(){if(!a.convertBinary||"arraybuffer"!=a.responseType&&"blob"!=a.responseType){if("arraybuffer"==a.responseType)return e.arrayBuffer();if("blob"==a.responseType)return e.blob();console.warn("xhr: responseType",a.responseType," is not implemented!");return e.text()}return e.arrayBuffer().then(function(a){return q.arrbuf2str(a)})}().then(function(a){d.response=
a;b()}):e.text().then(function(a){d.responseText=a;b()});else return d.responseXML=null,d.responseText="",d.response=null,{done:function(a){a()}};return{done:function(a){b=a}}}().done(function(){if(a.partialSize&&f.onpartial){var e=a.convertBinary&&d.response?d.response:d.responseText;["response","responseText","responseXML"].forEach(function(a){delete d[a]});e&&(e.length>a.partialSize?b(e):d.response_data=e)}c("onload",d);c("ondone",d)})}).catch(function(a){a=l({status:408,statusText:a.message||
"Request Timeout"});c("onerror",a);c("ondone",a)})}catch(e){console.error(e.stack),d=t(e.message),c("onerror",d),c("ondone",d)}return{abort:function(){try{p.abort&&p.abort()}catch(a){}}}},y=function(a,f,k,c,g){var l,b=new XMLHttpRequest(a.anonymous?{mozAnon:!0}:{}),d=function(m){var h="",c=a.url;if(2<b.readyState&&(h=b.getAllResponseHeaders(),4==b.readyState)){h&&(h=h.replace(/TM-finalURL[0-9a-zA-Z]*\: .*[\r\n]{1,2}/,""));var d=b.getResponseHeader("TM-finalURL"+rea.runtime.short_id);d&&(c=d)}h={readyState:b.readyState,
responseHeaders:h,finalUrl:c,status:4==b.readyState?b.status:0,statusText:4==b.readyState?b.statusText:""};m&&4==b.readyState?(b.responseType?(h.responseXML=null,h.responseText=null,h.responseType=b.responseType):(h.responseXML=b.responseXML,h.responseText=b.responseText),h.response=b.response):(h.responseXML=null,h.responseText="",h.response=null);return h},r=function(b){(function(a,b){for(var m=[],c=0,d=a.length;c<d;c+=b)m.push(a.slice(c,b+c));return m})(b,parseInt(a.partialSize)).forEach(function(a){g("onpartial",
{partial:a})})},p={onload:function(){var b=d(!0);4==b.readyState&&200!=b.status&&0!=b.status&&0<a.retries?(a.retries--,y(a,f,k,c,g)):function(){if(a.convertBinary&&b.response){var c=b.responseType?b.responseType.toLowerCase():"";if("blob"==c){var d,e=new FileReader;e.onload=function(){b.response=q.arrbuf2str(e.result);d()};e.readAsArrayBuffer(b.response);return{done:function(a){d=a}}}"arraybuffer"==c?b.response=q.arrbuf2str(b.response):"json"==c&&(b.response=JSON.stringify(b.response))}return{done:function(a){a()}}}().done(function(){if(a.partialSize&&
f.onpartial){var d=a.convertBinary&&b.response?b.response:b.responseText;["response","responseText","responseXML"].forEach(function(a){delete b[a]});d&&(d.length>a.partialSize?r(d):b.response_data=d)}c("onload",b);4==b.readyState&&c("ondone",b)})},onerror:function(){var b=d();4==b.readyState&&200!=b.status&&0!=b.status&&0<a.retries?(a.retries--,y(a,f,k,c,g)):(c("onerror",b),c("ondone",b))},onloadstart:function(){g("onloadstart",function(){return d()})},onreadystatechange:function(){g("onreadystatechange",
function(){return d()})},onprogress:function(a){g("onprogress",function(){var c=d(),e=c;void 0===e&&(e={});try{var f=null,g=null;if(a.lengthComputable||0<a.total)f=a.loaded,g=a.total;else{var k=Number(n.getStringBetweenTags(c.responseHeaders.toLowerCase(),"content-length:","\n").trim()),l=2<c.readyState&&b.responseText?b.responseText.length:0;0==k&&(k=-1);f=a.loaded||l;g=a.total||k}e.lengthComputable=a.lengthComputable;e.loaded=f;e.done=f;e.position=f;e.total=g;e.totalSize=g}catch(p){}return e})},
ontimeout:function(){var a=d();c("ontimeout");c("ondone",a)}},e=0==Object.keys(p).concat(["ondone"]).filter(function(a){return!!f[a]}).length;e||Object.keys(p).forEach(function(a){if(f[a]||-1!=["ontimeout","onload","onerror"].indexOf(a))b[a]=p[a]});try{if(!k.internal&&!z(a.url))throw Error("Invalid scheme of url: "+a.url);b.open(a.method,a.url,!e,a.user,a.password);if(a.headers||a.nocache){var v={};a.headers&&n.assign(v,a.headers);a.nocache&&n.assign(v,D);Object.keys(v).forEach(function(a){var c=
a;A[a.toLowerCase()]&&(c=w+a);b.setRequestHeader(c,v[a])})}void 0!==a.overrideMimeType&&b.overrideMimeType(a.overrideMimeType);void 0!==a.responseType&&(b.responseType=a.responseType);void 0!==a.timeout&&(b.timeout=a.timeout);void 0!==a.data?"typified"===a.data_type?b.send(u(a.data)):b.send(a.data):b.send()}catch(m){console.error(m.stack);var x=t(m.message);c("onerror",x);c("ondone",x);e&&(l=x)}l=l||(e?d():{});return n.copy({abort:function(){b.abort()}},l)};Registry.register("xmlhttprequest","5271",
function(a,f){r=f;w=a;return{run:E,makeErrorResponse:t}})});
